buy/urls.py
from django.urls import path
from . import views

app_name = 'buy'

urlpatterns = [
    # here name is name of the url
    path('',views.allProdCat, name = 'allProdCat'), # just all products
    path('<slug:c_slug>/',views.allProdCat, name = 'products_by_category'), # products will all categories
    path('<slug:c_slug>/<slug:p_slug>/',views.allProducts,name = 'each_product_details'),#
]

donate/urls.py
from django.urls import path
from . import views

app_name = 'donate'

urlpatterns = [
    # here name is name of the url
    path('',views.donate, name = 'donate'),
    path('donation/',views.viewExcel, name = 'excel'),
    path('sentemail',views.sendNoti, name = 'sendNoti'),

]

freshness/urls.py
from django.urls import path
from . import views

app_name = 'freshness'

urlpatterns = [
    # here name is name of the url
    path('',views.freshness, name = 'fresh'),
    path('importdata',views.import_data, name = 'freshdata'),
    path('predict',views.predict, name = 'predict_result'),
    path('reports',views.reports, name = 'reports'),
    path('analysis/overview-chart',views.overview_chart, name = 'overview-chart'),
    path('analysis/price-chart/',views.price_chart, name = 'price-chart'),
    path('analysis/price/',views.price, name = 'price'),
]

grocery/urls.py
from django.contrib import admin
from django.urls import path, include
from buy import views
from homepage.views import HomeView
from django.conf import settings
from django.conf.urls.static import static
from stock.views import StockChartView

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('',views.index,name = 'index'),
    path('stock/',StockChartView.as_view(), name = 'stock'),
    path('',HomeView.as_view(), name = 'home'),
    path('donate/',include('donate.urls')),
    path('freshness/',include('freshness.urls')),
    path('buy/',include('buy.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart.urls')),
    path('order/',include('order.urls')),
    path('accounts/create/',views.signupView,name = 'signup'),
    path('accounts/login/',views.signinView,name = 'signin'),
    path('accounts/logout/',views.signoutView,name = 'signout'),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

freshness/models.py
from django.db import models

# Create your models here.

class food(models.Model):
    item_no = models.CharField(max_length= 20)
    item = models.CharField(max_length= 20)
    description = models.CharField(max_length= 80)
    price= models.CharField(max_length= 20)
    temp = models.CharField(max_length= 20)
    humidity = models.CharField(max_length= 20)
    co2 = models.CharField(max_length = 20)
    o2 = models.CharField(max_length = 20)
    freshlevel = models.CharField(max_length = 10)

freshness/views.py
from .models import food
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, JsonResponse
import csv
from django.db.models import Sum


from freshness.freshness_classification import predict_freshness, cross_val, yPred, xTest

from django.db import connection
import pandas as pd
# Create your views here.
path = './staticfiles/data/Freshness_classification.csv'
cursor = connection.cursor()



def import_data(request):
    # cursor.execute('TRUNCATE TABLE freshness_food')
    food.objects.all().delete()
    
    with open(path) as f:
        reader = csv.reader(f)
        for row in reader:
            _, created = food.objects.get_or_create(
                item_no=row[0],
                item=row[1],
                description=row[2],
                price = row[3],
                temp = row[4],
                humidity = row[5],
                co2 = row[6],
                o2 = row[7],
                freshlevel = row[8],
                )
    text_var = 'Data has been successfully imported into database!'
    importdata = True
    return render(request, 'index.html',{'importdata':importdata})

def freshness(request):
	
	return render(request, 'index.html')

def predict(request):
    text_var = 'Predict successful!'
    predict_freshness()
    query = 'SELECT * FROM freshness_food'
    # cursor.execute('SELECT * FROM freshness_food ORDER BY item')
    # print(cursor.fetchall())
    table = pd.read_sql(query,connection)
    table = table.to_html()

    y_pred = pd.DataFrame(yPred())
    x_test = xTest()
    x_test = pd.DataFrame(x_test)
    y_pred.rename(columns={"0":"Prediction"})
    x_test.rename(columns={"0":"item","1":"Description"})
    table_pred = pd.concat([x_test,y_pred],axis=1,join='inner')
    table_pred = table_pred.to_html()
  
    scores = cross_val()
    return render(request,'subpage/prediction.html',{'table_pred':table_pred, 'table':table, 'scores':scores})

def reports(request):
    return render(request,'subpage/reports.html')


def overview_chart(request):
    queryset = food.objects.order_by('-price')[:5]
    labels = []
    data = []

    for fd in queryset:
        labels.append(fd.item)
        data.append(fd.price)

    return render(request,'analysis.html',{
        'labels':labels,
        'data':data,
    })

def price_chart(request):
    labels = []
    data = []

    queryset = food.objects.values('item').annotate(food_price=Sum('price')).order_by('-food_price')
    
    for entry in queryset:
        labels.append(entry['item'])
        data.append(entry['food_price'])
    
    return JsonResponse(data={
        'labels': labels,
        'data': data,
    })

def price(request):
    return render(request,'subpage/price.html')

freshness/templates/analysis.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <title>Dashboard Template · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/dashboard/">

    

    <!-- Bootstrap core CSS -->
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
  </head>
  <body>
    
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">iSmileTechnologies</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="nav-link" href="#">Sign out</a>
    </li>
  </ul>
</header>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'freshness:fresh' %}">
              <span data-feather="home"></span>
              Dashboard
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'freshness:freshdata' %}">
              <span data-feather="file"></span>
              Import Data
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'freshness:predict_result'%}">
              <span data-feather="shopping-cart"></span>
              Check Freshness
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'freshness:overview-chart' %}">
              <span data-feather="users"></span>
              Products
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'freshness:reports' %}">
              <span data-feather="bar-chart-2"></span>
              Reports
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="layers"></span>
              Integrations
            </a>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Saved reports</span>
          <a class="link-secondary" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Current month
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Last quarter
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Social engagement
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Year-end sale
            </a>
          </li>
        </ul>
      </div>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group me-2">
            <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'freshness:overview-chart'%}">Overview</a></button>
            <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'freshness:price'%}">Price Analysis</a></button>
          </div>
          <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
            <span data-feather="calendar"></span>
            This week
          </button>
        </div>
      </div>

        
        <canvas id="overview-chart"></canvas>
        

        <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
        <script>

            var config = {
            type: 'pie',
            data: {
                datasets: [{
                data: {{ data|safe }},
                backgroundColor: [
                    '#134356', '#808324', '#A65322', '#C0C052', '#D3D334'
                ],
                label: 'price'
                }],
                labels: {{ labels|safe }}
            },
            options: {
                responsive: true
            }
            };

            window.onload = function() {
            var ctx = document.getElementById('overview-chart').getContext('2d');
            window.myPie = new Chart(ctx, config);
            };

        </script> 
      
        
        
    </main>
  </div>
</div>


   <script src="{% static 'js/bootstrap.bundle.min.js'% }"></script>

      <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script><script src="{% static 'js/dashboard.js'% }"></script>
  </body>
</html>

freshness/templates/index.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <title>iSmileTechnologies</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/dashboard/">

    

    <!-- Bootstrap core CSS -->
    
  
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    
    {% comment %} <link rel="stylesheet" href="{% static 'css/dashboard.rtl.css' %}"> {% endcomment %}

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
    
    <!-- Custom styles for this template -->
    {% comment %} <link href="dashboard.css" rel="stylesheet"> {% endcomment %}
  </head>
  <body>
    
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="/">iSmileTechnologies</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="nav-link" href="#">Search</a>
    </li>
  </ul>
</header>

<div class="container-fluid">
  <div class="row">
  <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'freshness:fresh' %}">
              <span data-feather="home"></span>
              Dashboard
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'freshness:freshdata' %}">
              <span data-feather="file"></span>
              Import Data
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="predict">
              <span data-feather="shopping-cart"></span>
              Check Freshness
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'freshness:overview-chart' %}">
              <span data-feather="users"></span>
              Products
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'freshness:reports' %}">
              <span data-feather="bar-chart-2"></span>
              Reports
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="layers"></span>
              Integrations
            </a>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Saved reports</span>
          <a class="link-secondary" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Current month
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Last quarter
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Social engagement
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Year-end sale
            </a>
          </li>
        </ul>
      </div>
    </nav>  

  <div class = "ml-auto col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <main class="">

      {%if importdata%}
      <div class = "alert alert-success" role="alert">
        <strong>Great!</strong> Data has been successfully imported into database.
        <button type = "button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {%endif%}

      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Freshness Dashboard</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group me-2">
            <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
            <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
          </div>
          <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
            <span data-feather="calendar"></span>
            This week
          </button>
        </div>
      </div>

      {% comment %} <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas> {% endcomment %}
    
      <h2>Test Data</h2>
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th>#</th>
              <th>Header</th>
              <th>Header</th>
              <th>Header</th>
              <th>Header</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1,001</td>
              <td>Lorem</td>
              <td>ipsum</td>
              <td>dolor</td>
              <td>sit</td>
            </tr>
            <tr>
              <td>1,002</td>
              <td>amet</td>
              <td>consectetur</td>
              <td>adipiscing</td>
              <td>elit</td>
            </tr>
            <tr>
              <td>1,003</td>
              <td>Integer</td>
              <td>nec</td>
              <td>odio</td>
              <td>Praesent</td>
            </tr>
            <tr>
              <td>1,003</td>
              <td>libero</td>
              <td>Sed</td>
              <td>cursus</td>
              <td>ante</td>
            </tr>
            <tr>
              <td>1,004</td>
              <td>dapibus</td>
              <td>diam</td>
              <td>Sed</td>
              <td>nisi</td>
            </tr>
            <tr>
              <td>1,005</td>
              <td>Nulla</td>
              <td>quis</td>
              <td>sem</td>
              <td>at</td>
            </tr>
            <tr>
              <td>1,006</td>
              <td>nibh</td>
              <td>elementum</td>
              <td>imperdiet</td>
              <td>Duis</td>
            </tr>
            <tr>
              <td>1,007</td>
              <td>sagittis</td>
              <td>ipsum</td>
              <td>Praesent</td>
              <td>mauris</td>
            </tr>
            <tr>
              <td>1,008</td>
              <td>Fusce</td>
              <td>nec</td>
              <td>tellus</td>
              <td>sed</td>
            </tr>
            <tr>
              <td>1,009</td>
              <td>augue</td>
              <td>semper</td>
              <td>porta</td>
              <td>Mauris</td>
            </tr>
            <tr>
              <td>1,010</td>
              <td>massa</td>
              <td>Vestibulum</td>
              <td>lacinia</td>
              <td>arcu</td>
            </tr>
            <tr>
              <td>1,011</td>
              <td>eget</td>
              <td>nulla</td>
              <td>Class</td>
              <td>aptent</td>
            </tr>
            <tr>
              <td>1,012</td>
              <td>taciti</td>
              <td>sociosqu</td>
              <td>ad</td>
              <td>litora</td>
            </tr>
            <tr>
              <td>1,013</td>
              <td>torquent</td>
              <td>per</td>
              <td>conubia</td>
              <td>nostra</td>
            </tr>
            <tr>
              <td>1,014</td>
              <td>per</td>
              <td>inceptos</td>
              <td>himenaeos</td>
              <td>Curabitur</td>
            </tr>
            <tr>
              <td>1,015</td>
              <td>sodales</td>
              <td>ligula</td>
              <td>in</td>
              <td>libero</td>
            </tr>
          </tbody>
        </table>
      </div>

      

    </main>
    {% include 'footer.html' %}
  </div>

    
  </div>
  
</div>


    
    <script src="{% static 'js/bootstrap.bundle.min.js'% }"></script>
    <script src="{% static 'js/bootstrap.js'% }"></script>
      <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script>
      <script src="{% static 'js/dashboard.js'% }"></script>
      {% comment %} <script src="./static/js/dashboard.js"></script> {% endcomment %}
      
  </body>
</html>

freshness/templates/reports.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <title>Dashboard</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/dashboard/">

    

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% comment %} <link rel="stylesheet" href="{% static 'css/dashboard.rtl.css' %}"> {% endcomment %}

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
     <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
    
    <!-- Custom styles for this template -->
    {% comment %} <link href="dashboard.css" rel="stylesheet"> {% endcomment %}
  </head>
  <body>
    
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="/">iSmileTechnologies</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="nav-link" href="#">Search</a>
    </li>
  </ul>
</header>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'freshness:fresh' %}">
              <span data-feather="home"></span>
              Dashboard
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'freshness:freshdata' %}">
              <span data-feather="file"></span>
              Import Data
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="predict">
              <span data-feather="shopping-cart"></span>
              Check Freshness
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/importdata">
              <span data-feather="users"></span>
              Products
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'freshness:reports' %}">
              <span data-feather="bar-chart-2"></span>
              Reports
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="layers"></span>
              Integrations
            </a>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Saved reports</span>
          <a class="link-secondary" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Current month
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Last quarter
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Social engagement
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Year-end sale
            </a>
          </li>
        </ul>
      </div>
    </nav>

  <div class = "ml-auto col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <main>
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        
        
      </div>
        

      {% comment %} <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas> {% endcomment %}
          
    </main>
    {% include 'footer.html' %}
    </div>
  </div>
  
</div>


    
    <script src="{% static 'js/bootstrap.bundle.min.js'% }"></script>
    
      <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script><script src="{% static 'js/dashboard.js'% }"></script>
      {% comment %} <script src="./static/js/dashboard.js"></script> {% endcomment %}
      
  </body>
</html>