buy/urls.py
from django.urls import path
from . import views

app_name = 'buy'

urlpatterns = [
    # here name is name of the url
    path('',views.allProdCat, name = 'allProdCat'), # just all products
    path('<slug:c_slug>/',views.allProdCat, name = 'products_by_category'), # products will all categories
    path('<slug:c_slug>/<slug:p_slug>/',views.allProducts,name = 'each_product_details'),#
]

donate/urls.py
from django.urls import path
from . import views

app_name = 'donate'

urlpatterns = [
    # here name is name of the url
    path('',views.donate, name = 'donate'),
    path('donation/',views.viewExcel, name = 'excel'),
    path('sentemail',views.sendNoti, name = 'sendNoti'),

]

grocery/urls.py
from django.contrib import admin
from django.urls import path, include
from buy import views
from homepage.views import HomeView
from django.conf import settings
from django.conf.urls.static import static
from stock.views import StockChartView

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('',views.index,name = 'index'),
    path('stock/',StockChartView.as_view(), name = 'stock'),
    path('',HomeView.as_view(), name = 'home'),
    path('donate/',include('donate.urls')),
    path('freshness/',include('freshness.urls')),
    path('buy/',include('buy.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart.urls')),
    path('order/',include('order.urls')),
    path('accounts/create/',views.signupView,name = 'signup'),
    path('accounts/login/',views.signinView,name = 'signin'),
    path('accounts/logout/',views.signoutView,name = 'signout'),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

donate/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

donate/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
	first_name = forms.CharField(max_length=100, required=True)
	last_name = forms.CharField(max_length=100, required=True)
	email = forms.EmailField(max_length=254, help_text='eg. youremail@anyemail.com')

	class Meta:
		model = User
		fields = ('first_name','last_name','email','username','password1','password2')

donate/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse

from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.contrib.auth.models import Group, User

from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.views.generic import TemplateView

import pandas as pd
# from donate.emailNotificationDonation import sendEmail
# from html import HTML
# Create your views here.

file = 'donation.xls'

def index(request):
    text_var = 'This is customer donation app'
    return HttpResponse(text_var)

def donate(request):
	return render(request, 'donation/donapage.html')

def viewExcel(request):
    dishesList = pd.read_excel(file, sheet_name=0, index_col=0)
    excel = dishesList.to_html()

    return render(request, 'donation/donapage.html', {'excel': excel})

def sendNoti(request):
    # sendEmail()
    text_var = 'Email has been sent'
    return HttpResponse(text_var)
    # return render(request, 'donation/donapage.html')

donate/templates/donation/donapage.html
{% extends "donate.html" %}
{% load static %}
{% block metadescription %}
	Home Page
{% endblock %}
{% block title %}
	Home Page
{% endblock %}
{% block content %}
	<div>
			<div class="mx-auto">
				<br>
				<div class="container">
					
					<div class ="row">
						<h1 class="jumbotron-heading">Thanks for your donation!</h1>
					</div>
					<p><em>Below is the current stock.</em></p>
					
					<p>
						{%if not excel%}
							<a href="donation/" class="btn btn-primary">Check Stock</a>
						{%endif%}
					</p>

					{%if excel%}
						<div class="row justify-content-center">
							<div class="col-auto">
								<div class="table table-dark">

									{% autoescape off %}
										{{ excel }}
									{% endautoescape %} 
								</div>
							</div>
						</div>
						<div class="float-right">
							<a class="btn btn-outline-primary btn-circle float-right"href="{% url 'donate:sendNoti' %}">Notify</a>
						</div>
						<br>
					{%endif%}
		
				</div>
				

				
			</div>
			</div>
	</div>
	<br>
{% endblock %}